# NumPy陣列
## NumPy簡介
（本節無範例）
## NumPy陣列的產生
### 產生一般陣列

In [2]:
import numpy as np
arr = np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 產生特殊類型陣列

In [3]:
#產生一個以1為開始，15為結束，3為步長的隨機序列
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [4]:
#產生一個以1開始，15為結束，步長預設的隨機序列
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
#產生一個以15為結束，步長預設為1的隨機序列
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#產生長度為3的0陣列
np.zeros(3)

array([0., 0., 0.])

In [7]:
#產生2行3列的一個陣列
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#產生長度為3的1陣列
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#產生一個3×3的單位矩陣
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 產生亂數組

In [11]:
#產生長度為3的位於(0,1)之間的亂數組
np.random.rand(3)

array([0.70722584, 0.94509424, 0.96080697])

In [12]:
#產生2行3列值位於(0,1)之間的陣列
np.random.rand(2,3)

array([[0.85140368, 0.85135133, 0.97278996],
       [0.37296085, 0.83648412, 0.62759109]])

In [13]:
#產生長度為3的滿足常態分佈的亂數組
np.random.randn(3)

array([ 0.20302174, -0.48280116,  0.69908017])

In [14]:
#在區間[1,5)產生長度為10的亂數組
np.random.randint(1,5,10)

array([1, 1, 4, 1, 4, 3, 1, 2, 4, 1])

In [15]:
#在區間[0,5)上產生長度為10的亂數組
np.random.randint(5,size=10)

array([0, 2, 1, 1, 2, 1, 4, 0, 2, 2])

In [16]:
#在區間[0,5)產生2行3列的亂數組
np.random.randint(5,size = (2,3))

array([[1, 3, 2],
       [2, 2, 0]])

In [19]:
#從陣列a中選取2行3列的數值組成一個新的陣列
np.random.choice(5,(2,3))

array([[2, 3, 3],
       [1, 4, 2]])

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.shuffle(arr)
arr 

array([9, 8, 7, 4, 5, 1, 6, 3, 0, 2])

## NumPy陣列的基本屬性

In [22]:
#3行3列的陣列
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.shape

(3, 3)

In [24]:
#arr陣列共有9個元素
arr.size

9

In [25]:
#arr陣列的類型為int
arr.dtype

dtype('int32')

In [26]:
#arr陣列為2維陣列
arr.ndim

2

In [3]:
#arr1陣列為1維陣列
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
arr1.ndim

1

## NumPy陣列的資料選取
### 一維資料選取

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#取得第4位的數，即傳入3
arr[3]

3

In [11]:
#取得末端最後一個數值
arr[-1]

9

In [13]:
#取得末端倒數第二個數值
arr[-2]

8

In [14]:
#取得位置3到5的值，不包含位置5的值
arr[3:5]

array([3, 4])

In [15]:
#取得位置3以後的所有元素
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
#取得位置3之前的所有元素
arr[:3]

array([0, 1, 2])

In [17]:
#取得從第3位到倒數第2位的元素，不包括倒數第2位
arr[3:-2]

array([3, 4, 5, 6, 7])

In [18]:
#取得陣列中大於3的元素
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

### 多維資料選取

In [19]:
# 建立一個多維陣列供使用
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#取得第2列資料
arr[1]

array([4, 5, 6])

In [25]:
#取得第2列和第3列的資料，包括第3列
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
#取得第3列之前的所有行資料，不包括第3列
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#取得第2欄的資料
arr[:,1]

array([2, 5, 8])

In [28]:
#取得第1到3欄的資料，不包括第3欄
arr[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
#取得第3欄之前的所有欄，不包括第3欄
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [30]:
#取得第2欄之後的所有欄，包括第2欄
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [31]:
#取得第1到2列，第2到3欄的數據
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

## NumPy陣列的資料預處理
### NumPy陣列的類型轉換

In [32]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [33]:
#陣列arr的原資料類型為int32
arr.dtype

dtype('int32')

In [34]:
#將arr陣列從int類型轉換為float類型
arr_float = arr.astype(np.float64)
arr_float

array([0., 1., 2., 3., 4.])

In [35]:
arr_float.dtype

dtype('float64')

In [36]:
#將arr陣列從int類型轉換為str類型
arr_str = arr.astype(np.string_)
arr_str

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [37]:
arr_str.dtype

dtype('S11')

### NumPy陣列的缺失值處理

In [39]:
#建立一個含有缺失值的陣列，nan表示缺失值
arr = np.array([1,2,np.nan,4])
arr

array([ 1.,  2., nan,  4.])

In [40]:
# 第三位為缺失值
np.isnan(arr)

array([False, False,  True, False])

In [41]:
#用0填充
arr[np.isnan(arr)] = 0
arr

array([1., 2., 0., 4.])

### NumPy陣列的重複值處理

In [42]:
arr = np.array([1,2,3,2,1])
np.unique(arr)

array([1, 2, 3])

## NumPy陣列重塑
### 一維陣列重塑

In [43]:
#新增一個一維陣列
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
#將陣列重塑為4欄2列的多維陣列
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
#將陣列重塑為2欄4列的多維陣列
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### 多維陣列重塑

In [46]:
#新增一個多維陣列
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
#將陣列重塑為3欄4列
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
#將陣列重塑為6欄2列
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### 陣列轉置

In [49]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## NumPy陣列合併
### 橫向合併

In [51]:
# 先新增兩個陣列，用來進行合併
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [52]:
# concatenate方法
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [53]:
# hstack方法
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [54]:
# column_stack方法
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 縱向合併

In [55]:
# concatenate方法
np.concatenate([arr1,arr2],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
np.row_stack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 常用資料分析函式
### 元素級函式

In [58]:
#新增一個陣列
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [59]:
#求取各個元素的平方
np.square(arr)

array([0, 1, 4, 9], dtype=int32)

In [60]:
#求取各個元素的平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

### 描述統計函式

In [61]:
#新增一個陣列
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
#對整個陣列進行求和
arr.sum()

45

In [63]:
#對陣列中的每一列分別求和
arr.sum(axis = 1)

array([ 6, 15, 24])

In [65]:
#對陣列中的每一欄分別求和
arr.sum(axis = 0)

array([12, 15, 18])

In [66]:
#對整個陣列進行求均值
arr.mean()

5.0

In [67]:
#對陣列中的每一列分別求均值
arr.mean(axis = 1)

array([2., 5., 8.])

In [68]:
#對陣列中的每一欄分別求均值
arr.mean(axis = 0)

array([4., 5., 6.])

In [69]:
#對整個陣列求最大值
arr.max()

9

In [70]:
#對陣列中的每一列分別求最小值
arr.max(axis = 1)

array([3, 6, 9])

In [71]:
#對陣列中的每一欄分別求最大值
arr.max(axis = 0)

array([7, 8, 9])

### 條件函式

In [73]:
#新增一個陣列用來儲存學生成績
arr = np.array([56,61,65])
#大於60及格，小於60不及格
np.where(arr>60,"及格","不及格")

array(['不及格', '及格', '及格'], dtype='<U3')

In [74]:
#傳回滿足條件的值對應的位置
np.where(arr>60)

(array([1, 2], dtype=int64),)

### 集合關係

In [75]:
#新增兩個陣列
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,5])

In [76]:
#包含
np.in1d(arr1,arr2)

array([ True,  True, False, False])

In [77]:
#交集
np.intersect1d(arr1,arr2)

array([1, 2])

In [78]:
#並集
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5])

In [79]:
#差集
np.setdiff1d(arr1,arr2)

array([3, 4])